services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'contact'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    volumes:
      - ./local_db:/var/lib/mysql